Repository seo-rry-again/airflow, pull requests merged in 2025-07, with the labels that each got.

#16 chore: DAG, DBT, Glue CI/CD 파이프라인 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: chore

#7 feature: 이벤트 데이터 파이프라인 구현
  dags/event_data_pipeline.py
  team1_dbt/macros/get_custom_schema.sql
  team1_dbt/models/dim/dim_event.sql
  team1_dbt/models/example/my_first_dbt_model.sql
  team1_dbt/models/example/my_second_dbt_model.sql
  team1_dbt/models/example/schema.yml
  team1_dbt/models/fact/fact_event.sql
  team1_dbt/models/sources.yml
  team1_dbt/models/staging/stg_event.sql
Labels: feature

#12 feature: EC2 중단 시간대 기상 데이터 백필 파이프라인 구현
  dags/weather_data_backfill_night.py
  glue_jobs/weather_data_backfill_night.py
Labels: feature

#14 feature: EC2 중단 시간대 인구 데이터 백필 파이프라인 구현
  .gitignore
  dags/population_data_backfill_dag_night.py
  dags/population_pipeline.py
  glue_jobs/population_data_backfill_night.py
  team1_dbt/dbt_project.yml
  team1_dbt/macros/generate_schema_name.sql
  team1_dbt/models/fact/fact_population.sql
  team1_dbt/models/sources.yml
  team1_dbt/models/staging/stg_population.sql
Labels: feature

#8 feature: 상권 데이터 파이프라인 구현
  dags/commercial_data_pipeline_dag.py
  docker-compose.yaml
  team1_dbt/.dbt/profiles.template.yml
  team1_dbt/dbt_project.yml
  team1_dbt/macros/get_custom_schema.sql
  team1_dbt/models/fact/fact_commercial.sql
  team1_dbt/models/fact/fact_commercial_rsb.sql
  team1_dbt/models/sources.yml
  team1_dbt/models/staging/stg_commercial.sql
  team1_dbt/models/staging/stg_commercial_rsb.sql
  team1_dbt/packages.yml
Labels: feature

#11 feature: 교통 데이터 파이프라인 구현
  dags/transport_data_pipeline_dag.py
  requirements.txt
  team1_dbt/macros/get_custom_schema.sql
  team1_dbt/models/fact/fact_transport.sql
  team1_dbt/models/sources.yml
  team1_dbt/models/staging/stg_bus.sql
  team1_dbt/models/staging/stg_subway.sql
Labels: feature

#17 fix: Move commercial_data_backfill_night.py to glue_jobs directory
  glue_jobs/commercial_data_backfill_night.py
Labels: fix
